### ISSUE TITLE
Option to disable plugin's linting rules

### ISSUE THREAD

**Issue by lcmgh** [elegoff/sonar-rust#58]
Hello!

We would like to only rely on clippy lints and not use the lints from the plugin itself. Is there a way to disable the issue creating for those?

Thanks

**Comment by elegoff** [comment]
The plugin-specific lints are called "rules" in SonarQube terminology and are defined in SonarQube via [Quality profiles](https://docs.sonarqube.org/latest/instance-administration/quality-profiles/). There used to be a workaround with SonarQube < 9.1 with defining a Quality Profile with 0 rules and setting that as the default Quality Profile for all projects.

However, this is [no longer possible in recent versions of SonarQube](https://sonarsource.atlassian.net/browse/SONAR-13150) (>= 9.1) where at least 1 plugin rule has to be defined.

Could you elaborate on the reason you want to only rely on Clippy lints? What do you feel is wrong with plugin-specific lints (so that we might improve them maybe)?

**Comment by lcmgh** [comment]
I typically fix clippy lints during development so without questioning specific rules of your plugin I thought that it is sufficient to rely solely on clippy for the sake of simplicity and streamlining the workflow. On the other hand I would like to get useful lints that clippy is not aware of. 

I'm also lacking of knowledge if Sonar rules in general are more powerful (in terms of covering certain findings/edge cases). I think I like the idea of having one tool in place that benefits from the overall Rust community instead of introducing additional linters.

**Comment by elegoff** [comment]
Latest version of the plugin (v0.1.1) now works around the issue by setting a default Quality Profile with only one rule (because that's required by SonarQube) and that remaining rule should actually never kick in (only set for very long lines of code over 240 chars).
Therefore I believe your issue is addressed and I will close it
