### ISSUE TITLE
Version 0.1.4 is offered in SonarQube LTS 8.9.10, but prevents start after install

### ISSUE THREAD

**Issue by beyerjsb** [elegoff/sonar-rust#64]
SonarQube LTS 8.9.10 (the latest 8.x LTS version as of writing this issue) is offering Rust Language Analyzer 0.1.4 plugin for install.
Upon install and restart, SonarQube won't start anymore.
In the web.log: 
ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed: Plugin Rust language analyzer [communityrust] requires at least SonarQube 9.11.0.290

Other plugins don't let me install versions which don't work with the LTS version, like Checkstyle 10.5 - it would be great if this could be done for the Rust plugin in a similar fashion.

Additionally, the Plugin Compatibility Matrix at https://docs.sonarqube.org/latest/instance-administration/plugin-version-matrix/ shows version 0.1.4 for SonarQube 8.9 which is obviously not correct.

**Comment by elegoff** [comment]
Thanks for reporting this. You are correct that the Plugin Compatibility Matrix at https://docs.sonarqube.org/latest/instance-administration/plugin-version-matrix/ is currently wrong and should show version **0.1.0** as the most recent compatible with SonarQube 8.9

That said, [SonarQube most recent LTS version is now version 9.9 ](https://www.sonarsource.com/products/sonarqube/downloads/lts/9-9-lts/), which means that from now on every SonarQube 8.x is deprecated

Please note the error message is also misleading as the Rust plugin 0.1.4 is actually tested and working fine with SonarQube 9.9 LTS

At the moment, your options are therefore to either 
- stick to SonarQube 8.9.10 in combination with our plugin in version 0.1.0, 
- or upgarde the most recent SonarQube 9.9 LTS in combination with the latest Rust plugin (v 0.1.4 as of today)

You may manually upgrade/revert the plugin versions by placing the correct jar file version in the _extensions/plugins_  folder of your SonarQube instance. 

Please note, there should be only one version of the plugin at any given time
Manually upgrading or reverting a plugin always requires a SonarQube restart to be fully effective.

We will request to fix the Compatibility matrix when the next plugin release is out, so that SonarQube 8 users don't attempt to install our plugin with releases greater than 0.1.0

Now the SonarQube 8 series becomes officially deprecated, there will no longer be any new Rust plugins releases for any SonarQube versions older than SonarQube 9.9.0 LTS
